/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AvaliaOPessoal } from "../../avaliaOPessoal/base/AvaliaOPessoal";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { MeditaO } from "../../meditaO/base/MeditaO";
import { RecomendaO } from "../../recomendaO/base/RecomendaO";
import { RecursoAdicional } from "../../recursoAdicional/base/RecursoAdicional";
import { SessODeMeditaOGuiada } from "../../sessODeMeditaOGuiada/base/SessODeMeditaOGuiada";
import { SessODeTerapia } from "../../sessODeTerapia/base/SessODeTerapia";

@ObjectType()
class UsuRio {
  @ApiProperty({
    required: false,
    type: () => [AvaliaOPessoal],
  })
  @ValidateNested()
  @Type(() => AvaliaOPessoal)
  @IsOptional()
  avaliaOPessoals?: Array<AvaliaOPessoal>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  idade!: number | null;

  @ApiProperty({
    required: false,
    type: () => [MeditaO],
  })
  @ValidateNested()
  @Type(() => MeditaO)
  @IsOptional()
  meditaOs?: Array<MeditaO>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome!: string | null;

  @ApiProperty({
    required: false,
    type: () => [RecomendaO],
  })
  @ValidateNested()
  @Type(() => RecomendaO)
  @IsOptional()
  recomendaOs?: Array<RecomendaO>;

  @ApiProperty({
    required: false,
    type: () => [RecursoAdicional],
  })
  @ValidateNested()
  @Type(() => RecursoAdicional)
  @IsOptional()
  recursoAdicionals?: Array<RecursoAdicional>;

  @ApiProperty({
    required: false,
    type: () => [SessODeMeditaOGuiada],
  })
  @ValidateNested()
  @Type(() => SessODeMeditaOGuiada)
  @IsOptional()
  sessODeMeditaOGuiadas?: Array<SessODeMeditaOGuiada>;

  @ApiProperty({
    required: false,
    type: () => [SessODeTerapia],
  })
  @ValidateNested()
  @Type(() => SessODeTerapia)
  @IsOptional()
  sessODeTerapias?: Array<SessODeTerapia>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { UsuRio as UsuRio };
