/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AvaliaOPessoalUpdateManyWithoutUsuRiosInput } from "./AvaliaOPessoalUpdateManyWithoutUsuRiosInput";
import { ValidateNested, IsOptional, IsString, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { MeditaOUpdateManyWithoutUsuRiosInput } from "./MeditaOUpdateManyWithoutUsuRiosInput";
import { RecomendaOUpdateManyWithoutUsuRiosInput } from "./RecomendaOUpdateManyWithoutUsuRiosInput";
import { RecursoAdicionalUpdateManyWithoutUsuRiosInput } from "./RecursoAdicionalUpdateManyWithoutUsuRiosInput";
import { SessODeMeditaOGuiadaUpdateManyWithoutUsuRiosInput } from "./SessODeMeditaOGuiadaUpdateManyWithoutUsuRiosInput";
import { SessODeTerapiaUpdateManyWithoutUsuRiosInput } from "./SessODeTerapiaUpdateManyWithoutUsuRiosInput";

@InputType()
class UsuRioUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AvaliaOPessoalUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => AvaliaOPessoalUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => AvaliaOPessoalUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  avaliaOPessoals?: AvaliaOPessoalUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  idade?: number | null;

  @ApiProperty({
    required: false,
    type: () => MeditaOUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => MeditaOUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => MeditaOUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  meditaOs?: MeditaOUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecomendaOUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => RecomendaOUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => RecomendaOUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  recomendaOs?: RecomendaOUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: () => RecursoAdicionalUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => RecursoAdicionalUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => RecursoAdicionalUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  recursoAdicionals?: RecursoAdicionalUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: () => SessODeMeditaOGuiadaUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => SessODeMeditaOGuiadaUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => SessODeMeditaOGuiadaUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  sessODeMeditaOGuiadas?: SessODeMeditaOGuiadaUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: () => SessODeTerapiaUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => SessODeTerapiaUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => SessODeTerapiaUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  sessODeTerapias?: SessODeTerapiaUpdateManyWithoutUsuRiosInput;
}

export { UsuRioUpdateInput as UsuRioUpdateInput };
