/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompartilhamentoSocialUpdateManyWithoutUsuRiosInput } from "./CompartilhamentoSocialUpdateManyWithoutUsuRiosInput";
import { ValidateNested, IsOptional, IsString, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { DesempenhoDoUsuRioUpdateManyWithoutUsuRiosInput } from "./DesempenhoDoUsuRioUpdateManyWithoutUsuRiosInput";
import { MetasFitnesUpdateManyWithoutUsuRiosInput } from "./MetasFitnesUpdateManyWithoutUsuRiosInput";
import { PlanoDeTreinoUpdateManyWithoutUsuRiosInput } from "./PlanoDeTreinoUpdateManyWithoutUsuRiosInput";
import { RealizaEsERecompensasUpdateManyWithoutUsuRiosInput } from "./RealizaEsERecompensasUpdateManyWithoutUsuRiosInput";

@InputType()
class UsuRioUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CompartilhamentoSocialUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => CompartilhamentoSocialUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => CompartilhamentoSocialUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  compartilhamentoSocials?: CompartilhamentoSocialUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: () => DesempenhoDoUsuRioUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => DesempenhoDoUsuRioUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => DesempenhoDoUsuRioUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  desempenhoDoUsuRios?: DesempenhoDoUsuRioUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  idade?: number | null;

  @ApiProperty({
    required: false,
    type: () => MetasFitnesUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => MetasFitnesUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => MetasFitnesUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  metasFitnesItems?: MetasFitnesUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome?: string | null;

  @ApiProperty({
    required: false,
    type: () => PlanoDeTreinoUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => PlanoDeTreinoUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => PlanoDeTreinoUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  planoDeTreinos?: PlanoDeTreinoUpdateManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: () => RealizaEsERecompensasUpdateManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => RealizaEsERecompensasUpdateManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => RealizaEsERecompensasUpdateManyWithoutUsuRiosInput, {
    nullable: true,
  })
  realizaEsERecompensasItems?: RealizaEsERecompensasUpdateManyWithoutUsuRiosInput;
}

export { UsuRioUpdateInput as UsuRioUpdateInput };
