/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompartilhamentoSocialCreateNestedManyWithoutUsuRiosInput } from "./CompartilhamentoSocialCreateNestedManyWithoutUsuRiosInput";
import { ValidateNested, IsOptional, IsString, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { DesempenhoDoUsuRioCreateNestedManyWithoutUsuRiosInput } from "./DesempenhoDoUsuRioCreateNestedManyWithoutUsuRiosInput";
import { MetasFitnesCreateNestedManyWithoutUsuRiosInput } from "./MetasFitnesCreateNestedManyWithoutUsuRiosInput";
import { PlanoDeTreinoCreateNestedManyWithoutUsuRiosInput } from "./PlanoDeTreinoCreateNestedManyWithoutUsuRiosInput";
import { RealizaEsERecompensasCreateNestedManyWithoutUsuRiosInput } from "./RealizaEsERecompensasCreateNestedManyWithoutUsuRiosInput";

@InputType()
class UsuRioCreateInput {
  @ApiProperty({
    required: false,
    type: () => CompartilhamentoSocialCreateNestedManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => CompartilhamentoSocialCreateNestedManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => CompartilhamentoSocialCreateNestedManyWithoutUsuRiosInput, {
    nullable: true,
  })
  compartilhamentoSocials?: CompartilhamentoSocialCreateNestedManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: () => DesempenhoDoUsuRioCreateNestedManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => DesempenhoDoUsuRioCreateNestedManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => DesempenhoDoUsuRioCreateNestedManyWithoutUsuRiosInput, {
    nullable: true,
  })
  desempenhoDoUsuRios?: DesempenhoDoUsuRioCreateNestedManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  idade?: number | null;

  @ApiProperty({
    required: false,
    type: () => MetasFitnesCreateNestedManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => MetasFitnesCreateNestedManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => MetasFitnesCreateNestedManyWithoutUsuRiosInput, {
    nullable: true,
  })
  metasFitnesItems?: MetasFitnesCreateNestedManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome?: string | null;

  @ApiProperty({
    required: false,
    type: () => PlanoDeTreinoCreateNestedManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => PlanoDeTreinoCreateNestedManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => PlanoDeTreinoCreateNestedManyWithoutUsuRiosInput, {
    nullable: true,
  })
  planoDeTreinos?: PlanoDeTreinoCreateNestedManyWithoutUsuRiosInput;

  @ApiProperty({
    required: false,
    type: () => RealizaEsERecompensasCreateNestedManyWithoutUsuRiosInput,
  })
  @ValidateNested()
  @Type(() => RealizaEsERecompensasCreateNestedManyWithoutUsuRiosInput)
  @IsOptional()
  @Field(() => RealizaEsERecompensasCreateNestedManyWithoutUsuRiosInput, {
    nullable: true,
  })
  realizaEsERecompensasItems?: RealizaEsERecompensasCreateNestedManyWithoutUsuRiosInput;
}

export { UsuRioCreateInput as UsuRioCreateInput };
