/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompartilhamentoSocial } from "../../compartilhamentoSocial/base/CompartilhamentoSocial";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { DesempenhoDoUsuRio } from "../../desempenhoDoUsuRio/base/DesempenhoDoUsuRio";
import { MetasFitnes } from "../../metasFitnes/base/MetasFitnes";
import { PlanoDeTreino } from "../../planoDeTreino/base/PlanoDeTreino";
import { RealizaEsERecompensas } from "../../realizaEsERecompensas/base/RealizaEsERecompensas";

@ObjectType()
class UsuRio {
  @ApiProperty({
    required: false,
    type: () => [CompartilhamentoSocial],
  })
  @ValidateNested()
  @Type(() => CompartilhamentoSocial)
  @IsOptional()
  compartilhamentoSocials?: Array<CompartilhamentoSocial>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [DesempenhoDoUsuRio],
  })
  @ValidateNested()
  @Type(() => DesempenhoDoUsuRio)
  @IsOptional()
  desempenhoDoUsuRios?: Array<DesempenhoDoUsuRio>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  idade!: number | null;

  @ApiProperty({
    required: false,
    type: () => [MetasFitnes],
  })
  @ValidateNested()
  @Type(() => MetasFitnes)
  @IsOptional()
  metasFitnesItems?: Array<MetasFitnes>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome!: string | null;

  @ApiProperty({
    required: false,
    type: () => [PlanoDeTreino],
  })
  @ValidateNested()
  @Type(() => PlanoDeTreino)
  @IsOptional()
  planoDeTreinos?: Array<PlanoDeTreino>;

  @ApiProperty({
    required: false,
    type: () => [RealizaEsERecompensas],
  })
  @ValidateNested()
  @Type(() => RealizaEsERecompensas)
  @IsOptional()
  realizaEsERecompensasItems?: Array<RealizaEsERecompensas>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { UsuRio as UsuRio };
