/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompartilhamentoSocialListRelationFilter } from "../../compartilhamentoSocial/base/CompartilhamentoSocialListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DesempenhoDoUsuRioListRelationFilter } from "../../desempenhoDoUsuRio/base/DesempenhoDoUsuRioListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { MetasFitnesListRelationFilter } from "../../metasFitnes/base/MetasFitnesListRelationFilter";
import { PlanoDeTreinoListRelationFilter } from "../../planoDeTreino/base/PlanoDeTreinoListRelationFilter";
import { RealizaEsERecompensasListRelationFilter } from "../../realizaEsERecompensas/base/RealizaEsERecompensasListRelationFilter";

@InputType()
class UsuRioWhereInput {
  @ApiProperty({
    required: false,
    type: () => CompartilhamentoSocialListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CompartilhamentoSocialListRelationFilter)
  @IsOptional()
  @Field(() => CompartilhamentoSocialListRelationFilter, {
    nullable: true,
  })
  compartilhamentoSocials?: CompartilhamentoSocialListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DesempenhoDoUsuRioListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DesempenhoDoUsuRioListRelationFilter)
  @IsOptional()
  @Field(() => DesempenhoDoUsuRioListRelationFilter, {
    nullable: true,
  })
  desempenhoDoUsuRios?: DesempenhoDoUsuRioListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  idade?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => MetasFitnesListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MetasFitnesListRelationFilter)
  @IsOptional()
  @Field(() => MetasFitnesListRelationFilter, {
    nullable: true,
  })
  metasFitnesItems?: MetasFitnesListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nome?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PlanoDeTreinoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PlanoDeTreinoListRelationFilter)
  @IsOptional()
  @Field(() => PlanoDeTreinoListRelationFilter, {
    nullable: true,
  })
  planoDeTreinos?: PlanoDeTreinoListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RealizaEsERecompensasListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RealizaEsERecompensasListRelationFilter)
  @IsOptional()
  @Field(() => RealizaEsERecompensasListRelationFilter, {
    nullable: true,
  })
  realizaEsERecompensasItems?: RealizaEsERecompensasListRelationFilter;
}

export { UsuRioWhereInput as UsuRioWhereInput };
