/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DesempenhoDoUsuRioListRelationFilter } from "../../desempenhoDoUsuRio/base/DesempenhoDoUsuRioListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PlanoDeTreinoWhereUniqueInput } from "../../planoDeTreino/base/PlanoDeTreinoWhereUniqueInput";

@InputType()
class ExercCioWhereInput {
  @ApiProperty({
    required: false,
    type: () => DesempenhoDoUsuRioListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DesempenhoDoUsuRioListRelationFilter)
  @IsOptional()
  @Field(() => DesempenhoDoUsuRioListRelationFilter, {
    nullable: true,
  })
  desempenhoDoUsuRios?: DesempenhoDoUsuRioListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  duraOMinutos?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nome?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PlanoDeTreinoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PlanoDeTreinoWhereUniqueInput)
  @IsOptional()
  @Field(() => PlanoDeTreinoWhereUniqueInput, {
    nullable: true,
  })
  planoDeTreino?: PlanoDeTreinoWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  tipo?: StringNullableFilter;
}

export { ExercCioWhereInput as ExercCioWhereInput };
