/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, PerfilDoUsuRio as PrismaPerfilDoUsuRio } from "@prisma/client";

export class PerfilDoUsuRioServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PerfilDoUsuRioCountArgs, "select">
  ): Promise<number> {
    return this.prisma.perfilDoUsuRio.count(args);
  }

  async perfilDoUsuRios<T extends Prisma.PerfilDoUsuRioFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PerfilDoUsuRioFindManyArgs>
  ): Promise<PrismaPerfilDoUsuRio[]> {
    return this.prisma.perfilDoUsuRio.findMany<Prisma.PerfilDoUsuRioFindManyArgs>(
      args
    );
  }
  async perfilDoUsuRio<T extends Prisma.PerfilDoUsuRioFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PerfilDoUsuRioFindUniqueArgs>
  ): Promise<PrismaPerfilDoUsuRio | null> {
    return this.prisma.perfilDoUsuRio.findUnique(args);
  }
  async createPerfilDoUsuRio<T extends Prisma.PerfilDoUsuRioCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PerfilDoUsuRioCreateArgs>
  ): Promise<PrismaPerfilDoUsuRio> {
    return this.prisma.perfilDoUsuRio.create<T>(args);
  }
  async updatePerfilDoUsuRio<T extends Prisma.PerfilDoUsuRioUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PerfilDoUsuRioUpdateArgs>
  ): Promise<PrismaPerfilDoUsuRio> {
    return this.prisma.perfilDoUsuRio.update<T>(args);
  }
  async deletePerfilDoUsuRio<T extends Prisma.PerfilDoUsuRioDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PerfilDoUsuRioDeleteArgs>
  ): Promise<PrismaPerfilDoUsuRio> {
    return this.prisma.perfilDoUsuRio.delete(args);
  }
}
