/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  SessODeMeditaOGuiada as PrismaSessODeMeditaOGuiada,
  UsuRio as PrismaUsuRio,
} from "@prisma/client";

export class SessODeMeditaOGuiadaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SessODeMeditaOGuiadaCountArgs, "select">
  ): Promise<number> {
    return this.prisma.sessODeMeditaOGuiada.count(args);
  }

  async sessODeMeditaOGuiadas<
    T extends Prisma.SessODeMeditaOGuiadaFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.SessODeMeditaOGuiadaFindManyArgs>
  ): Promise<PrismaSessODeMeditaOGuiada[]> {
    return this.prisma.sessODeMeditaOGuiada.findMany<Prisma.SessODeMeditaOGuiadaFindManyArgs>(
      args
    );
  }
  async sessODeMeditaOGuiada<
    T extends Prisma.SessODeMeditaOGuiadaFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.SessODeMeditaOGuiadaFindUniqueArgs>
  ): Promise<PrismaSessODeMeditaOGuiada | null> {
    return this.prisma.sessODeMeditaOGuiada.findUnique(args);
  }
  async createSessODeMeditaOGuiada<
    T extends Prisma.SessODeMeditaOGuiadaCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.SessODeMeditaOGuiadaCreateArgs>
  ): Promise<PrismaSessODeMeditaOGuiada> {
    return this.prisma.sessODeMeditaOGuiada.create<T>(args);
  }
  async updateSessODeMeditaOGuiada<
    T extends Prisma.SessODeMeditaOGuiadaUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.SessODeMeditaOGuiadaUpdateArgs>
  ): Promise<PrismaSessODeMeditaOGuiada> {
    return this.prisma.sessODeMeditaOGuiada.update<T>(args);
  }
  async deleteSessODeMeditaOGuiada<
    T extends Prisma.SessODeMeditaOGuiadaDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.SessODeMeditaOGuiadaDeleteArgs>
  ): Promise<PrismaSessODeMeditaOGuiada> {
    return this.prisma.sessODeMeditaOGuiada.delete(args);
  }

  async getUsuRio(parentId: string): Promise<PrismaUsuRio | null> {
    return this.prisma.sessODeMeditaOGuiada
      .findUnique({
        where: { id: parentId },
      })
      .usuRio();
  }
}
